# https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

name: Artifacts - Upload and Download

on: [push]

jobs:
  #// https://github.com/actions/upload-artifact#upload-an-individual-file
  job-build:
    name: BUILD stage - (upload one file)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- run: mkdir -p test_path/artifact
    #- run: echo hello > test_path/artifact/world.txt
    - run: echo Hello World > hello.txt
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        #path: test_path/artifact/world.txt
        path: hello.txt

  job-release:
    name: RELEASE stage - (download file above)
    runs-on: ubuntu-latest
    #// NOTE: *needs* `job-build` above
    needs: job-build
    steps:
      #// https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#downloading-artifacts-during-a-workflow-run
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
